### ISSUE TITLE
I wanna cry

### ISSUE THREAD

**Issue by MedicMedic** [VemAiensi/VemAiensi.github.io#2]
I thought I was only gonna do JavaScript, but here I am, still touching HTML.

All the elements need an ID. The text boxes must be read-only. Is there even a text box for the result, or are we appending it to the text?

Should I bother with .js files, or should I stick everything in index.html? What would make you cry less?

My tendency to settle for "good enough" is challenged by your mere existence, and it's both annoying and probably also good for me.

I'm gonna sleep. I want to leave this wretched city right after class and ignore everyone I don't care about once I'm home.

**Comment by VemAiensi** [comment]
Oh I haven't read this until now
